-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  --
-- default Monitor config

-- Monitor Configuration
-- See Hyprland wiki for more details
-- https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

-- MIGRATION NOTE: `monitor = NAME, MODE, POSITION, SCALE` becomes hl.monitor() with
-- named fields. An empty NAME (the old `monitor=,preferred,auto,1`) is a catch-all and
-- becomes `output = ""`. As before, later rules for the same output win — so of the
-- three active rules below, `highres` is the one that takes effect.

-- Monitors
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- High Refresh Rate
hl.monitor({ output = "", mode = "highrr", position = "auto", scale = 1 })

-- High Resolution
hl.monitor({ output = "", mode = "highres", position = "auto", scale = 1 })

-- NOTE: for laptop, kindly check notes in UserConfigs/Laptops.lua regarding display
-- Created this inorder for the monitor display to not wake up if not intended.
-- See here: https://github.com/hyprwm/Hyprland/issues/4090

-- Some examples to set your own monitor
-- hl.monitor({ output = "eDP-1",     mode = "preferred",    position = "auto", scale = 1 })
-- hl.monitor({ output = "eDP-1",     mode = "2560x1440@165", position = "0x0", scale = 1 }) -- own screen
-- hl.monitor({ output = "DP-3",      mode = "1920x1080@240", position = "auto", scale = 1 })
-- hl.monitor({ output = "DP-1",      mode = "preferred",    position = "auto", scale = 1 })
-- hl.monitor({ output = "HDMI-A-1",  mode = "preferred",    position = "auto", scale = 1 })

-- QEMU-KVM, virtual box or vmware
-- hl.monitor({ output = "Virtual-1", mode = "1920x1080@60", position = "auto", scale = 1 })

-- to disable a monitor
-- MIGRATION NOTE: the old `monitor=name,disable` is now the `disabled` field.
-- hl.monitor({ output = "name", disabled = true })

-- Mirror samples
-- MIGRATION NOTE: the old trailing `,mirror,<source>` is now the `mirror` field.
-- hl.monitor({ output = "DP-3",     mode = "1920x1080@60",  position = "0x0", scale = 1, mirror = "DP-2" })
-- hl.monitor({ output = "",         mode = "preferred",     position = "auto", scale = 1, mirror = "eDP-1" })
-- hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@144", position = "0x0", scale = 1, mirror = "eDP-1" })

-- 10 bit monitor support - See wiki https://wiki.hypr.land/Configuring/Basics/Monitors/ - See NOTES below
-- NOTE: Colors registered in Hyprland (e.g. the border color) do not support 10 bit.
-- NOTE: Some applications do not support screen capture with 10 bit enabled. (Screen captures like OBS may render black screen)
-- MIGRATION NOTE: the old trailing `,bitdepth,10` is now the `bitdepth` field.
-- hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1, bitdepth = 10 })

-- MIGRATION NOTE: `monitor=eDP-1,transform,0` and `,addreserved,...` are now fields on
-- the monitor's own rule rather than separate lines.
-- hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1, transform = 0 })
-- hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1,
--              reserved = { top = 10, right = 10, bottom = 10, left = 49 } })

-- workspaces - Monitor rules
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- SUPER SHIFT E - Workspace-Rules
-- See ~/.config/hypr/workspaces.lua (generated by nwg-displays)
