-- Generated by nwg-displays on 2026-07-28 at 08:16:16. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.02",
    position = "969x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1680x1050@59.88",
    position = "2889x0",
    scale = 1.0
})
