-- Generated by nwg-displays on 2026-06-16 at 08:15:08. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1"
})
